### ISSUE TITLE
responsive feature

### ISSUE THREAD

**Issue by mortennh** [tomoyukikashiro/Sketch-bootstrap-guides#1]
It would be great if this plugin would support different viewports. Like when i create an artboard with an width of 375px, it then automatically creates a grid which fits and so on

**Comment by t-jindai** [comment]
@moesphemie thanks for your comments.
I added support for small screens.

Plz re-install latest version. 👍 
https://github.com/tomoyukikashiro/Sketch-bootstrap-guides/releases/tag/1.1.0
